### ISSUE TITLE
spelling error for "quiet"

### ISSUE THREAD

**Issue by vsoch** [rohitfarmer/singularity-defs#1]
hey @rohitfarmer ! One of the contributors to the singularity catalog noticed that a lot of your R images have a spelling mistake, specifically "quite" instead of "quiet" you can see with a search on your repository:

https://github.com/rohitfarmer/singularity-defs/search?q=quite

**Comment by rohitfarmer** [comment]
Hi, @vsoch thank you for pointing that out; I just noticed that it only throws a warning, not a fatal error; that is why I never caught the typo. I will update the recipes.

**Comment by vsoch** [comment]
Thank you!
